### PR TITLE
Test

### PR DESCRIPTION
**Pull request by mchehab**

### CODE REVIEW

**Comment by ssrlive** [comment]
What a disaster! Please replace the tabs with 4 spaces or 8 spaces.

image

**Comment by mchehab** [comment]
> What a disaster! Please replace the tabs with 4 spaces or 8 spaces.

Tabs indent to 8 spaces. It sounds that your editor is using a non-standard indent for tabs.

**Comment by ssrlive** [comment]
I would still like you to replace tabs with spaces, so that will make the performance consistent in all editors.

**Comment by mchehab** [comment]
> I would still like you to replace tabs with spaces, so that will make the performance consistent in all editors.

Using spaces instead of tabs is not nice for my workflow. Most of my work is at the Linux Kernel, whose coding style is to always use tabs (8 spaces) for indent. So, the editor I use is set to indent using tabs.

Perhaps a compromise solution would be to change the indent to 8 spaces and increase the maximum line size, but I need to double check how to configure it with clang-format in a way that it would try to keep ~80 columns width (but allowing exceptions).

**Pull request merged**
