### PR TITLE
Missing config.h added.

### PR DESCRIPTION
**Pull request by ssrlive**
Missing config.h and more added.

Signed-off-by: ssrlive <ssrlivebox@gmail.com>

### CODE REVIEW

**Comment by hosiet** [comment]
Using `#include <config.h>` might be erroneous. Did you mean `#include "config.h"` ?

**Comment by ssrlive** [comment]
I think it is `#include <config.h>`, 

you can see this example.

https://github.com/mchehab/zbar/blob/a87e7c782fb95ad714a0d41acfdd1a9f1ea18487/zbar/video.h#L26

**Comment by hosiet** [comment]
OK, looks like it's the case according to https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Configuration-Headers.html .

**Comment by mchehab** [comment]
> Using `#include <config.h>` might be erroneous. Did you mean `#include "config.h"` ?

ZBar is using `#include <config.h>`. I actually prefer using  `#include "config.h"`, as it makes clearer that this file is from the project, and not from the system's library, but the best would be to replace it everywhere on a separate patch.

> OK, looks like it's the case according to https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Configuration-Headers.html .

Yeah, several projects do that. This is somewhat deprecated on newer projects, afaikt.

**Comment by mchehab** [comment]
Patch merged, thanks!

**Pull request closed without merging**
