### PR TITLE
Merge Debian packaging 0.10+doc-11 minus patches

### PR DESCRIPTION
**Pull request by jasp00**
Integrate changes done by @hosiet.

### CODE REVIEW

**Comment by mchehab** [comment]
I merged at master.
If not a problem for you, I would prefer to merge from master into stable-0.21 and finally release version 0.21.
The changes from stable-0.21 to master are basically:
- Regression test now checks all symbologies, including EAN variants;
- d-bus code was at the wrong place... it is now at image scanner where it should be since the beginning;
- zbarcam-qt now allows selecting protocols and enabling d-bus dynamically. Due to that, there are some new APIs that should be backward-compatible.

**Comment by jasp00** [comment]
>I merged at master.

Then closing...

**Comment by mchehab** [comment]
ZBar 0.21 released.

**Comment by mchehab** [comment]
It sounds that this patch added some new symbols to libzbarqt.so, probably due to some different compilation options.

That's a hunk with warnings when building stable-0.21 (see https://travis-ci.org/mchehab/zbar/builds/492679859 for full log):

```
 libzbarqt.so.0 libzbarqt0 #MINVER#
 * Build-Depends-Package: libzbarqt-dev
  (c++)"QList<QEvent*>::append(QEvent* const&)@Base" 0.20.1
- (c++)"QList<QEvent*>::detach_helper(int)@Base" 0.20.1
- (c++)"QList<QEvent*>::detach_helper_grow(int, int)@Base" 0.20.1
- (c++)"QList<QEvent*>::~QList()@Base" 0.20.1
+#MISSING: 0.21.1# (c++)"QList<QEvent*>::detach_helper(int)@Base" 0.20.1
+#MISSING: 0.21.1# (c++)"QList<QEvent*>::detach_helper_grow(int, int)@Base" 0.20.1
+#MISSING: 0.21.1# (c++)"QList<QEvent*>::~QList()@Base" 0.20.1
  (c++)"QString::~QString()@Base" 0.10
  (c++)"QVector<QPair<int, QString> >::reallocData(int, int, QFlags<QArrayData::AllocationOption>)@Base" 0.20.1
+ _ZN4zbar10QZBarImageC2ERK6QImage@Base 0.21.1
+ _ZN4zbar11QZBarThread10set_configENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE@Base 0.21.1
+ _ZN4zbar11QZBarThread9pushEventEP6QEvent@Base 0.21.1
+ _ZN4zbar14SymbolIteratorC2ERKNS_9SymbolSetE@Base 0.21.1
+ _ZN4zbar14SymbolIteratorD2Ev@Base 0.21.1
+ _ZN4zbar14SymbolIteratorppEv@Base **0.21.1**
+ _ZN4zbar6Symbol4initEPKNS_13zbar_symbol_sE@Base 0.21.1
+ _ZN5QListIP6QEventE5eraseENS2_8iteratorE@Base 0.21.1
+ _ZN5QListIP6QEventE9takeFirstEv@Base 0.21.1
+ _ZN7QVectorI5QPairIi7QStringEEaSEOS3_@Base 0.21.1
+ _ZN9QtPrivate19QVariantValueHelperI6QImageE8metaTypeERK8QVariant@Base 0.21.1
+ _ZNK4zbar5Image12symbol_beginEv@Base 0.21.1
+ _ZNK7QString11toStdStringB5cxx11Ev@Base 0.21.1
```

**Comment by jasp00** [comment]
You are pointing to the Clang build. It is fine.

**Comment by mchehab** [comment]
> You are pointing to the Clang build. It is fine.

Weird that it would produce different results depending on the compiler... the ABI symbols should not change if the compiler changes.

This entire ABI check logic at debian sounds too messy for my eyes :-)

Here, building on Ubuntu 18.04 and using dpkg-gensymbols/c++filt on g++, the produced file has 3 symbols less:

```
- (c++)"QList<QEvent*>::~QList()@Base" 0.20.1
- (c++)"void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag)@Base" 0.21
- (c++)"void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag)@Base" 0.20.1
```

**Comment by hosiet** [comment]
The C++ symbols system was fundamentally delicate and Debian's symbol system was working well for C libraries but cannot handle C++ well.

My suggestion: it's okay if you use this system to check if you have accidentally modified/deleted any symbols (of your own project, not anything from the standard C++ library) to keep API compatibility but don't integrate it into upstream development; it's work for downstream distribution maintainers.

**Comment by mchehab** [comment]
> My suggestion: it's okay if you use this system to check if you have accidentally modified/deleted any symbols (of your own project, not anything from the standard C++ library) to keep API compatibility but don't integrate it into upstream development; it's work for downstream distribution maintainers.

Surely it is up to distro maintainers to maintain the stuff there at the downstream repositories, with may or may not be identical to what we have at ZBar's `debian/` directory<sup>1</sup>.
<ul><sup>1</sup>Btw, for Ubuntu 18.04, the stuff there requires a change, as <code>apt</code> can't solve this dependency: <code>debhelper-compat (= 12)</code>.</ul>

Yet, IMHO, it would makes sense to update the `zbar/debian/*.symbols` at the upstream version as new symbols get added, like, for example, on this change: https://github.com/mchehab/zbar/commit/1bb3cb3c8bb5d14ac50983ad6e950bea612ee39b.

**Pull request closed without merging**
