### PR TITLE
 Add Travis CI builds

### LINKED ISSUE #11: Enable Travis CI
Before opening the pull request that adds continuous integration support, @mchehab, [Travis CI](https://travis-ci.org/) should be enabled for this repository. This way, the request should be automatically tested.

### PR DESCRIPTION
**Pull request by jasp00**
This request adds initial configuration for Travis CI. Let us see whether the builds start. Do not merge yet.

Closes #11.

### CODE REVIEW

**Comment by mchehab** [comment]
I added some patches meant to make it build on Windows today.

TravisCI is now complaining about the build on sid:

https://travis-ci.org/mchehab/zbar/builds/524433520?utm_medium=notification&utm_source=email

The problem doesn't seem related at all with the applied patches. It is basically failing during package install.

@jasp00 care to take a look on it?

**Comment by hosiet** [comment]
@mchehab I think the error log is very clear that openjdk 8 is no longer available in Debian Sid. Debian is moving onto OpenJDK 11 now. Please consider updating your dependency if the whole code is compatible with Java 11.

**Comment by mchehab** [comment]
> @mchehab I think the error log is very clear that openjdk 8 is no longer available in Debian Sid. Debian is moving onto OpenJDK 11 now. Please consider updating your dependency if the whole code is compatible with Java 11.

Hmm... never tested it with Java 11. Currently, I don't have Sid installed on any of my machines. If you have it installed, could you please check if it runs fine? Checking it should be as easy as:


```
$ export JAVA_HOME=/usr/lib/jvm/...
$ ./configure
$ make
$ make check-java

```

(assuming that the current code at autoconf will properly detect the java11 dependencies - there are some "black magic" there)

**Comment by mchehab** [comment]
Hmm... Fedora has an optional openjdk11 devel package. Just tested it here:

```
$ make check-java
make -C java check-java
make[1]: Entering directory '/devel/v4l/zbar/java'
  CC       libzbarjni_la-zbarjni.lo
  CCLD     libzbarjni.la
echo "making check in java"
making check in java
cd /devel/v4l/zbar/java; /usr/lib/jvm/java-11-openjdk-11.0.2.7-7.fc29.x86_64//bin/javac -classpath /devel/v4l/zbar/java/zbar.jar:.:/usr/share/java/junit.jar:/usr/share/java/hamcrest/all.jar:. -d /devel/v4l/zbar/java test/TestImage.java test/TestImageScanner.java test/TestScanImage.java
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
/devel/v4l/zbar/libtool -dlopen /devel/v4l/zbar/zbar/libzbar.la -dlopen /devel/v4l/zbar/java/libzbarjni.la --mode=execute /usr/lib/jvm/java-11-openjdk-11.0.2.7-7.fc29.x86_64//bin/java -Xcheck:jni -classpath zbar.jar:.:/usr/share/java/junit.jar:/usr/share/java/hamcrest/all.jar:. org.junit.runner.JUnitCore TestImage TestImageScanner TestScanImage
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
JUnit version 4.12
....................
Time: 0,043

OK (20 tests)
```

Seems to work fine

**Comment by mchehab** [comment]
Either jni.h is on a different package (on Fedora, it is), or the "magic" to discover java home doesn't work anymore with openjdk11:

```
cd /build/zbar-0.21.1/java; /usr/bin/javac -d /build/zbar-0.21.1/build-nopython/java net/sourceforge/zbar/Config.java net/sourceforge/zbar/Modifier.java net/sourceforge/zbar/Orientation.java net/sourceforge/zbar/Symbol.java net/sourceforge/zbar/SymbolIterator.java net/sourceforge/zbar/SymbolSet.java net/sourceforge/zbar/Image.java net/sourceforge/zbar/ImageScanner.java
  CC       libzbarjni_la-zbarjni.lo
/build/zbar-0.21.1/java/zbarjni.c:26:10: fatal error: jni.h: No such file or directory
 #include <jni.h>
          ^~~~~~~
```

Full log at: https://travis-ci.org/mchehab/zbar/jobs/524565322

**Pull request merged**
